# ------------------------ #
# Configuration des Builds #
# ------------------------ #

variables:
    GIT_SUBMODULE_STRATEGY: recursive

# ---------------------- #
# Compilation des Sujets #
# ---------------------- #

sujets:
    script:
        - ./scripts/make-statement.sh
    artifacts:
        paths:
            - tp/TP*.pdf
    tags:
        - marathon-sujet
